[package]
name = "rust"
version = "0.1.0"
authors = ["Yury Solovyov <invokedynamic@yandex.com>"]
edition = "2018"

[dependencies]
redis = { version = "0.17.0", features = ["tokio-comp"] }
serde = { version = "1.0.113", features = ["derive"] }
serde_json = "1.0.58"
